[package]
name = "grove"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
grove-domain = { workspace = true }
grove-proto = { workspace = true }
ratatui = "0.29"
crossterm = "0.28"
signal-hook = "0.3"
grove-lua = { workspace = true }
